### ISSUE TITLE
Hooking should maybe follow jumps.

### ISSUE THREAD

**Issue by Convery** [AyriaPublic/Plugintemplate_cpp#2]
The current hooking module just places a stomphook at the address, but more than one plugin may want to hook the same function. So we should consider making a hooktype that follows the jumps and then calls each in reverse order.

**Comment by sokie** [comment]
This would be pretty useful!
It's kinda the problem I had as well.

**Comment by Convery** [comment]
Partially implemented in 4b9726141b502fff028037b62af0fdc94943d437
